// Licensed under the Apache-2.0 License
// https://github.com/sator-imaging/ZeroSerializer

extern alias Sandbox;

using System;
using System.Reflection;
using Xunit;

#pragma warning disable CS1591  // Missing XML comment for publicly visible type or member

namespace ZeroSerializer.Tests
{
    public sealed class UnityCompatibilityTests
    {
        [Fact]
        public void RunSandboxCompatibilityTest()
        {
            // Retrieve the Sandbox assembly
            Assembly sandboxAssembly = typeof(Sandbox::FixedPacket).Assembly;

            // Find the Program type generated by top-level statements
            Type programType = sandboxAssembly.GetType("Program")
                ?? throw new InvalidOperationException("Could not find 'Program' type in ZeroSerializer.Sandbox assembly.");

            // Find the entry point method (usually <Main>$ or Main)
            MethodInfo entryPoint = programType.GetMethod("<Main>$", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)
                ?? programType.GetMethod("Main", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)
                ?? throw new InvalidOperationException("Could not find entry point method in 'Program' type.");

            // Invoke the entry point
            // For top-level statements, the method might accept string[] args
            ParameterInfo[] parameters = entryPoint.GetParameters();
            object[]? invokeArgs = parameters.Length == 1 ? new object[] { Array.Empty<string>() } : null;

            entryPoint.Invoke(null, invokeArgs);
        }

        [Fact]
        public void VerifyAlwaysFailThrowsException()
        {
            // Verify that calling SandboxHelper.AlwaysFail() throws the expected exception
            var exception = Assert.Throws<InvalidOperationException>(() => Sandbox::SandboxHelper.AlwaysFail());
            Assert.Equal("Intentional sandbox failure.", exception.Message);
        }

        [Fact]
        public void VerifySandboxAssemblyTargetFrameworkIsNetStandard21()
        {
            // Retrieve the Sandbox assembly
            Assembly sandboxAssembly = typeof(Sandbox::FixedPacket).Assembly;

            // Retrieve TargetFrameworkAttribute
            var targetFrameworkAttr = sandboxAssembly.GetCustomAttribute<System.Runtime.Versioning.TargetFrameworkAttribute>();

            Assert.NotNull(targetFrameworkAttr);
            Assert.Equal(".NETStandard,Version=v2.1", targetFrameworkAttr.FrameworkName);
        }

        [Fact]
        public void NestedStructPropertiesUseGeneratedViewTypes()
        {
            Assembly sandboxAssembly = typeof(Sandbox::FixedPacket).Assembly;
            Type packedPositionViewType = sandboxAssembly.GetType("ZeroSerializer.PackedPositionView")
                ?? throw new InvalidOperationException("Could not find generated PackedPositionView type.");
            Type fixedPacketViewType = sandboxAssembly.GetType("ZeroSerializer.FixedPacketView")
                ?? throw new InvalidOperationException("Could not find generated FixedPacketView type.");
            Type packedPacketViewType = sandboxAssembly.GetType("ZeroSerializer.PackedPacketView")
                ?? throw new InvalidOperationException("Could not find generated PackedPacketView type.");
            Type variablePacketViewType = sandboxAssembly.GetType("ZeroSerializer.VariablePacketView")
                ?? throw new InvalidOperationException("Could not find generated VariablePacketView type.");

            Assert.Equal(packedPositionViewType, fixedPacketViewType.GetProperty(nameof(Sandbox::FixedPacket.Position))?.PropertyType);
            Assert.Equal(packedPositionViewType, packedPacketViewType.GetProperty(nameof(Sandbox::PackedPacket.Position))?.PropertyType);
            Assert.Equal(
                typeof(Nullable<>).MakeGenericType(packedPositionViewType),
                variablePacketViewType.GetProperty(nameof(Sandbox::VariablePacket.OptionalPosition))?.PropertyType);
        }
    }
}
