// Licensed under the Apache-2.0 License
// https://github.com/sator-imaging/ZeroSerializer

extern alias UnityCompatibility;

using System;
using System.Reflection;
using System.Runtime.Versioning;
using Xunit;

#pragma warning disable CS1591  // Missing XML comment for publicly visible type or member

namespace ZeroSerializer.Tests
{
    public sealed class UnityCompatibilityTests
    {
        [Fact]
        public void UnityCompatibilityAssemblyExecutesSuccessfully()
        {
            // Retrieve the UnityCompatibility assembly
            Assembly unityAssembly = typeof(UnityCompatibility::FixedPacket).Assembly;

            // Find the Program type generated by top-level statements
            Type programType = unityAssembly.GetType("Program")
                ?? throw new InvalidOperationException("Could not find 'Program' type in ZeroSerializer.UnityCompatibilityTests assembly.");

            // Find the entry point method (usually <Main>$ or Main)
            MethodInfo entryPoint = programType.GetMethod("<Main>$", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)
                ?? programType.GetMethod("Main", BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic)
                ?? throw new InvalidOperationException("Could not find entry point method in 'Program' type.");

            // Invoke the entry point
            // For top-level statements, the method might accept string[] args
            ParameterInfo[] parameters = entryPoint.GetParameters();
            object[]? invokeArgs = parameters.Length == 1 ? new object[] { Array.Empty<string>() } : null;

            entryPoint.Invoke(null, invokeArgs);
        }

        [Fact]
        public void AlwaysFailHelperThrowsExpectedException()
        {
            // Verify that calling UnityCompatibilityHelper.AlwaysFail() throws the expected exception
            var exception = Assert.Throws<InvalidOperationException>(() => UnityCompatibility::UnityCompatibilityHelper.AlwaysFail());
            Assert.Equal("Intentional failure for verifying CI workflow correctness.", exception.Message);
        }

        [Fact]
        public void UnityCompatibilityAssemblyTargetsNetStandard21()
        {
            // Retrieve the UnityCompatibility assembly
            Assembly unityAssembly = typeof(UnityCompatibility::FixedPacket).Assembly;

            // Retrieve TargetFrameworkAttribute
            var targetFrameworkAttr = unityAssembly.GetCustomAttribute<TargetFrameworkAttribute>();

            Assert.NotNull(targetFrameworkAttr);
            Assert.Equal(".NETStandard,Version=v2.1", targetFrameworkAttr.FrameworkName);
        }
    }
}
