name: Test

on:
  push:
    branches: [ main ]
    paths-ignore: [ '.github/**' ]
  pull_request:
    paths-ignore: [ '.github/**' ]
  workflow_dispatch:

  # github.event_name, or other context data are propagated from caller.
  # No way to detect whether or not this workflow is called by other.
  workflow_call:
    inputs:
      __called:
        type: boolean
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    strategy:
      matrix:
        configuration: [Release, Debug]

    # FIX: cannot use ubuntu-latest
    runs-on: ubuntu-22.04   # tip: runs-on can use ${{ matrix.<name> }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5      # v4.3.1
      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9  # v4.3.1
        with:
          dotnet-version: |
            10.x.x
            9.x.x
            8.x.x
            7.x.x
            6.x.x
            5.x.x

      # !!! MUST NOT REMOVE THIS !!!
      # As test project cannot use netstandard2.1,
      # tests-unity project uses it instead for Unity compatibility test.
      - run: dotnet restore
      - run: dotnet build -c ${{ matrix.configuration }} --no-restore

      - run: |
          dotnet test -c ${{ matrix.configuration }} --no-restore --no-build \
            > test-output.txt 2>&1

          grep -E " - .*\.dll" test-output.txt >> $GITHUB_STEP_SUMMARY

      - if: failure()
        run: cat test-output.txt


  # Place after test to make step summary order better (test -> code preview)
  generated-source-preview:
    uses: ./.github/workflows/generated-source-preview.yml
